import React, { forwardRef } from 'react';
import type { DomainAnalysis } from '../../types';

interface PdfReportProps {
  analysis: DomainAnalysis;
  logoDataUrl: string;
}

const PdfReport = forwardRef<HTMLDivElement, PdfReportProps>(({ analysis, logoDataUrl }, ref) => {
  const { domain, brandability, seoStrength, estimatedValue, summary, colorPalette, tagline, domainAge } = analysis;

  return (
    <div ref={ref} className="bg-brand-dark text-gray-200 p-10 font-sans" style={{ width: '800px' }}>
      <header className="border-b-2 border-indigo-500 pb-4 mb-8 text-center">
        <h1 className="text-4xl font-bold text-white">Domain Appraisal Report</h1>
        <p className="text-2xl font-mono text-cyan-400 mt-2">{domain}</p>
      </header>

      <main>
        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-indigo-400 mb-4">Core Metrics</h2>
          <div className="grid grid-cols-4 gap-6 text-center">
            <div className="bg-brand-gray p-4 rounded-lg">
              <p className="text-sm text-gray-400">Brandability</p>
              <p className="text-3xl font-bold">{brandability}/10</p>
            </div>
            <div className="bg-brand-gray p-4 rounded-lg">
              <p className="text-sm text-gray-400">SEO Strength</p>
              <p className="text-3xl font-bold">{seoStrength}/10</p>
            </div>
             <div className="bg-brand-gray p-4 rounded-lg">
              <p className="text-sm text-gray-400">Domain Age</p>
              <p className="text-3xl font-bold">{domainAge}</p>
            </div>
            <div className="bg-brand-gray p-4 rounded-lg">
              <p className="text-sm text-gray-400">Estimated Value</p>
              <p className="text-3xl font-bold">${estimatedValue.toLocaleString()}</p>
            </div>
          </div>
        </section>

        <section className="mb-8 bg-brand-gray p-6 rounded-lg">
          <h2 className="text-2xl font-semibold text-indigo-400 mb-3">AI Summary</h2>
          <p className="text-gray-300 leading-relaxed">{summary}</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-indigo-400 mb-4">Branding Kit</h2>
          <div className="bg-brand-gray p-6 rounded-lg space-y-6">
            <div>
              <h3 className="font-semibold text-gray-200 text-lg">Suggested Tagline</h3>
              <p className="text-xl italic text-cyan-400">"{tagline}"</p>
            </div>
             <div className="grid grid-cols-2 gap-6">
                <div>
                    <h3 className="font-semibold text-gray-200 text-lg">Color Palette</h3>
                    <div className="flex space-x-4 mt-2">
                        {colorPalette.map(color => (
                        <div key={color} className="w-16 h-16 rounded-full border-2 border-brand-light-gray" style={{ backgroundColor: color }}></div>
                        ))}
                    </div>
                </div>
                <div>
                    <h3 className="font-semibold text-gray-200 text-lg">Logo Suggestion</h3>
                    <div className="w-24 h-24 rounded-lg bg-brand-light-gray flex-shrink-0 flex items-center justify-center mt-2">
                        {logoDataUrl ? (
                            <img src={logoDataUrl} alt="AI generated logo" className="w-full h-full rounded-lg object-cover" />
                        ) : (
                            <p className="text-xs text-gray-400">No Logo</p>
                        )}
                    </div>
                </div>
            </div>
          </div>
        </section>
      </main>

      <footer className="text-center text-gray-500 text-xs mt-10 pt-4 border-t border-brand-light-gray">
        <p>Generated by 🌐 DomainOgen.com &copy; {new Date().getFullYear()}</p>
        <p>This report is AI-generated and intended for informational purposes. Values are estimates.</p>
      </footer>
    </div>
  );
});

export default PdfReport;